/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PerProjectQuota } from './perProjectQuota';
import { Quota } from './quota';


/**
 * Represents a set of quotas assocated with an account
 */
export interface AccountQuota {
    /**
     * Gets the tier of user
     */
    tier?: string;
    /**
     * Gets the project quota
     */
    projects?: Quota;
    /**
     * Gets the prediction quota
     */
    predictions?: Quota;
    /**
     * Gets a list of quotas that apply per-project for each project
     */
    perProject?: Array<PerProjectQuota>;
}
