/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountQuota } from './accountQuota';
import { ApiKeys } from './apiKeys';


/**
 * Represents a user account
 */
export interface Account {
    /**
     * Gets the name of the account owner
     */
    userName?: string;
    /**
     * Gets the email associated with this account
     */
    email?: string;
    /**
     * Gets the api keys associated with this account
     */
    keys?: ApiKeys;
    /**
     * Gets the quotas associated with this account
     */
    quotas?: AccountQuota;
}
