/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageTagPrediction } from './imageTagPrediction';


/**
 * result of an image prediction request
 */
export interface ImagePredictionResult {
    id?: string;
    project?: string;
    iteration?: string;
    created?: Date;
    predictions?: Array<ImageTagPrediction>;
}
