/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Image } from './image';


export interface ImageCreateResult {
    sourceUrl?: string;
    status?: ImageCreateResult.StatusEnum;
    image?: Image;
}
export namespace ImageCreateResult {
    export type StatusEnum = 'OK' | 'OKDuplicate' | 'ErrorSource' | 'ErrorImageFormat' | 'ErrorImageSize' | 'ErrorStorage' | 'ErrorLimitExceed' | 'ErrorTagLimitExceed' | 'ErrorUnknown';
    export const StatusEnum = {
        OK: 'OK' as StatusEnum,
        OKDuplicate: 'OKDuplicate' as StatusEnum,
        ErrorSource: 'ErrorSource' as StatusEnum,
        ErrorImageFormat: 'ErrorImageFormat' as StatusEnum,
        ErrorImageSize: 'ErrorImageSize' as StatusEnum,
        ErrorStorage: 'ErrorStorage' as StatusEnum,
        ErrorLimitExceed: 'ErrorLimitExceed' as StatusEnum,
        ErrorTagLimitExceed: 'ErrorTagLimitExceed' as StatusEnum,
        ErrorUnknown: 'ErrorUnknown' as StatusEnum
    }
}
