/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageTag } from './imageTag';
import { PredictionTag } from './predictionTag';


/**
 * Image model to be sent as JSON
 */
export interface Image {
    id?: string;
    created?: Date;
    width?: number;
    height?: number;
    imageUri?: string;
    thumbnailUri?: string;
    tags?: Array<ImageTag>;
    predictions?: Array<PredictionTag>;
}
