/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Iteration model to be sent over JSON
 */
export interface Iteration {
    /**
     * Gets the id of the iteration
     */
    id?: string;
    /**
     * Gets or sets the name of the iteration
     */
    name?: string;
    /**
     * Gets or sets a value indicating whether the iteration is the default iteration for the project
     */
    isDefault?: boolean;
    /**
     * Gets the current iteration status
     */
    status?: string;
    /**
     * Gets the time this iteration was completed
     */
    created?: Date;
    /**
     * Gets the time this iteration was last modified
     */
    lastModified?: Date;
    /**
     * Gets the time this iteration was last modified
     */
    trainedAt?: Date;
    /**
     * Gets the project id of the iteration
     */
    projectId?: string;
    /**
     * Whether the iteration can be exported to another format for download
     */
    exportable?: boolean;
    /**
     * Get or sets a guid of the domain the iteration has been trained on
     */
    domainId?: string;
}
