/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagPerformance } from './tagPerformance';


/**
 * Represents the detailed performance data for a trained iteration
 */
export interface IterationPerformance {
    /**
     * Gets the per-tag performance details for this iteration
     */
    perTagPerformance?: Array<TagPerformance>;
    /**
     * Gets the precision
     */
    precision?: number;
    /**
     * Gets the standard deviation for the precision
     */
    precisionStdDeviation?: number;
    /**
     * Gets the recall
     */
    recall?: number;
    /**
     * Gets the standard deviation for the recall
     */
    recallStdDeviation?: number;
}
