/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quota } from './quota';


/**
 * Represents a set of quotas for a given project
 */
export interface PerProjectQuota {
    /**
     * Gets the project id of the project this quota applies to
     */
    projectId?: string;
    /**
     * Gets the iteration quota for the project
     */
    iterations?: Quota;
    /**
     * Gets the image quota for the project
     */
    images?: Quota;
    /**
     * Gets the tag quota for the project
     */
    tags?: Quota;
}
