/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectSettings } from './projectSettings';


/**
 * Represents a project
 */
export interface Project {
    /**
     * Gets the project id
     */
    id?: string;
    /**
     * Gets or sets the name of the project
     */
    name?: string;
    /**
     * Gets or sets the description of the project
     */
    description?: string;
    /**
     * Gets or sets the project settings
     */
    settings?: ProjectSettings;
    /**
     * Gets the current iteration id
     */
    currentIterationId?: string;
    /**
     * Gets the date this project was created
     */
    created?: Date;
    /**
     * Gets the date this project was last modifed
     */
    lastModified?: Date;
    /**
     * Gets the thumbnail url representing the image
     */
    thumbnailUri?: string;
}
