/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a quota
 */
export interface Quota {
    /**
     * The total allowable amount in the quota
     */
    total?: number;
    /**
     * The amount of quota that has currently been used
     */
    used?: number;
    /**
     * Gets the time remaining until the quota resets. Null if this quota does not reset.
     */
    timeUntilReset?: string;
}
