/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a Tag
 */
export interface Tag {
    /**
     * Gets the Tag ID
     */
    id?: string;
    /**
     * Gets or sets the name of the tag
     */
    name?: string;
    /**
     * Gets or sets the description of the tag
     */
    description?: string;
    /**
     * Gets the number of images with this tag
     */
    imageCount?: number;
}
