/**
 * Custom Vision Training 1.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents performance data for a particular tag in a trained iteration
 */
export interface TagPerformance {
    id?: string;
    name?: string;
    /**
     * Gets the precision
     */
    precision?: number;
    /**
     * Gets the standard deviation for the precision
     */
    precisionStdDeviation?: number;
    /**
     * Gets the recall
     */
    recall?: number;
    /**
     * Gets the standard deviation for the recall
     */
    recallStdDeviation?: number;
}
